### PR TITLE
Update moodle-plugin-ci

### PR DESCRIPTION
**Pull request by aspark21**
- Latest template from https://github.com/moodlehq/moodle-plugin-ci/blob/main/gha.dist.yml
- Matrix for 4.1-4.4 + main

### CODE REVIEW

**Comment by aspark21** [comment]
Run of it here - https://github.com/aspark21/moodle-qtype_regexp/actions/runs/8961362606

All looking good across versions bar the behat tests :)

**Comment by rezeau** [comment]
@aspark21 Thanks for trying to help, but I need your help again. I think I have done everything possible but I am still getting lots of failed checks on my question type. What am I doing wrong? Please note that when I run behat tests on my local host all is OK!

**Comment by aspark21** [comment]
@rezeau my colleague got it working, it’s just missing the plugin dependencies during the ci run
https://github.com/aydevworks/moodle-qtype_regexp/commit/7de1b4be2dda91db9f5174a7f4da75da04dc6dc3


https://github.com/aydevworks/moodle-qtype_regexp/actions/runs/9030872433

**Comment by rezeau** [comment]
Finally got it to work, thanks a lot for your help.
Don't know how to solve the last message in the list above "This branch has conflicts that must be resolved". Maybe you should refresh your fork of my regexp plugin repo?

**Comment by rezeau** [comment]
fixed

**Pull request closed without merging**
